- hosts: devvm
  become: true
  roles:
  - python
  - docker
  - docker-compose
  tasks:
  - name: greate git dir
    file:
      state: directory
      path: /home/fiercepc/DogGenerator
  - name: clone repo
    git:
      repo: https://github.com/michelle548129/DogGenerator
      dest: /home/fiercepc/DogGenerator
  vars: 
    docker_user: fiercepc

- hosts: ciservers
  become: true
  roles:
  - python
  - docker
  - docker-compose
  - jenkins
  vars:
    docker_user: jenkins

- hosts: swarmmanagers
  become: true
  roles:
  - docker
  - swarm-manager  
  tasks:
  - name: add ansible user to docker group
    user:
      name: fiercepc
      groups: docker
      append: yes
  vars:
    docker_user: jenkins

- hosts: swarmworkers
  become: true
  roles:
  - docker 
  - swarm-worker
  vars:
    docker_user: fiercepc

- hosts: webserver
  become: true
  roles:
  - docker 
  vars:
    docker_user: fiercepc
